**2016-09-21 - MapServer 7.0.2 is released**

The maintenance release of MapServer 7.0.2 is now available.
See the :ref:`7.0.2 changelog <changelog-7-0-2>`
for the full list of changes.

Head to :ref:`download` to obtain a copy.

**2016-02-25 - MapServer 7.0.1 and 6.4.3, and MapCache 1.4.1 are released**

The maintenance versions of MapServer 7.0 and 6.4 have been released.
See the :ref:`7.0.1 changelog <changelog-7-0-1>` and :ref:`6.4.3 changelog <changelog-6-4-3>`
for the full list of changes.

The maintenance release 1.4.1 of MapCache has been released.

Head to :ref:`download` to obtain a copy.

**2015-07-24 - MapServer 7.0.0 and MapCache 1.4 are released**

The major version MapServer 7.0 has been released. The list of significant
changes for this release can be found in the :ref:`7.0 announcement <announce-7-0>`.
See the :ref:`changelog <changelog-7-0-0>` for the full list
of changes since beta2.

MapCache version 1.4 has been released. The list of significant changes can be
found in the :ref:`1.4 announcement <announce-mapcache-1-4>`.

Head to :ref:`download` to obtain a copy.

**2015-06-26 - MapServer 7.0.0-beta2, MapServer 6.4.2 and TinyOWS 1.1.1 are released**

This is a security release to mitigate the effects of an issue in older versions of libxml2 (<2.9).
You are strongly recommended to update your systems if using an unpatched version of libxml2 < 2.9 as
it may lead to the information disclosure of any file readable by the user running the mapserver
services.

MapServer 7.0 beta2 is being simultaneously released and contains a number of fixes to issues that
were discovered during the beta1 test phase. Please help us pushing out a final 7.0 by testing this
beta and reporting any issues you may have.

 * :ref:`7.0-beta2 changelog <changelog-7-0-0-beta2>`
 * :ref:`6.4.2 changelog <changelog-6-4-2>`

Head to :ref:`download` to obtain a copy.

**2015-02-12 - MapServer 7.0.0-beta1 is released**

The first beta for MapServer 7.0 has been released. The list of
major changes for this release can be found in the :ref:`7.0 announcement <announce-7-0>`.
See the :ref:`changelog <changelog-7-0>`
for the full list of changes and head to :ref:`download` to obtain a copy.
