**2019-09-14 - MapServer 7.4.2 is released**

The maintenance release of MapServer 7.4.2 is now available.
See the :ref:`7.4 changelog <changelog-7-4>` for the full list of changes.  

Head to :ref:`download` to obtain a copy.

**2019-07-24 - MapCache 1.8.0 is released**

The major version MapCache 1.8.0 has been released. The list of significant
changes for this release can be found in the :ref:`changelog <changelog-mapcache-1-8>`.

Head to :ref:`download` to obtain a copy.

**2019-07-17 - MapCache 1.8.0-rc2 is released**

The second release candidate of MapCache 1.8.0 is now available.
See the :ref:`1.8.0-rc2 changelog <changelog-mapcache-1-8-0-rc2>`
for the full list of changes.  

Head to :ref:`download <dev-release>` to obtain a copy.

**2019-07-12 - MapServer 7.4.1 is released**

The maintenance release of MapServer 7.4.1 is now available.
See the :ref:`7.4 changelog <changelog-7-4>` for the full list of changes.  

Head to :ref:`download` to obtain a copy.

**2019-07-09 - MapCache 1.8.0-rc1 is released**

The first release candidate of MapCache 1.8.0 is now available.
See the :ref:`1.8.0-rc1 changelog <changelog-mapcache-1-8-0-rc1>`
for the full list of changes.  

Head to :ref:`download <dev-release>` to obtain a copy.

**2019-05-15 - MapServer 7.4.0 is released**

The major version MapServer 7.4.0 has been released. The list of significant
changes for this release can be found in the :ref:`7.4 announcement <announce-7-4>`.
See the :ref:`changelog <changelog-7-4>` for the full list
of changes.

Head to :ref:`download` to obtain a copy.
