**2013-08-14 - MapServer 6.4.0-beta1 is released**

The first beta for MapServer 6.4 has been released. The list of
major changes for this release can be found in the `HISTORY.TXT <https://github.com/mapserver/mapserver/blob/rel-6-4-0-beta1/HISTORY.TXT>`__
file from the source directory. See :ref:`the changelog <changelog-6-4>`
for the full list of changes and head to :ref:`download` to obtain a copy.

**2013-04-19 - MapServer 6.2.1 is released**

MapServer 6.2.1 has been released.  See :ref:`the changelog <changelog-6-2-1>`
for more details and head to :ref:`download` to obtain a copy.

**2012-11-14 - MapServer Suite 12.11 is released**

The first MapServer Suite, numbered 12.11, and containing MapServer 6.2.0, MapCache
1.0.0 and TinyOWS 1.1.0 has been released. See :ref:`the release announcement <announce-6-2>`
for more details and head to :ref:`download` to obtain a copy.

**2012-11-14 - MapServer 6.2.0 is released**

MapServer 6.2.0 has been released. See :ref:`the release announcement <announce-6-2>`
for more details, :ref:`the changelog since RC1 <changelog-6-2-0>` and head
to :ref:`download` to obtain a copy.

**2012-10-10 - MapServer 6.2.0 RC1 is released**

MapServer 6.2.0-RC1 has been released.  See :ref:`the changelog <changelog-6-2-0-rc1>`
for more details and head to :ref:`download` to obtain a copy.

**2012-05-18 - MapServer 6.0.3 is released**

MapServer 6.0.3 has been released.  See `the release announcement <http://lists.osgeo.org/pipermail/mapserver-users/2012-May/072329.html>`__
for more details and head to :ref:`download` to obtain a copy.

**2012-02-08 - TinyOWS 1.0.0 is released**

TinyOWS 1.0.0 has been released.  See `the release announcement <http://lists.osgeo.org/pipermail/mapserver-users/2012-February/071478.html>`__
for more details. (Note that TinyOWS will be part of the MapServer project starting with version 6.2)
