.. table:: \:ref\: reference labels

	============================   =============================================================================================
	Label                          Title
	============================   =============================================================================================
	about                          :ref:`About <about>`
	agg                            :ref:`AGG Rendering Specifics <agg>`
	antialias                      :ref:`AntiAliasing with MapServer <antialias>`
	arcinfo                        :ref:`ArcInfo <arcinfo>`
	arcsde                         :ref:`ArcSDE <arcsde>`
	autotest                       :ref:`Regression Testing <autotest>`
	background                     :ref:`Tutorial Timeframe <tutorial_background>`
	batch_utilities                :ref:`Batch Scripting <batch_utilities>`
	bugs                           :ref:`Bug Submission <bugs>`
	cgi                            :ref:`CGI <cgi>`
	cgi_controls                   :ref:`MapServer CGI Controls <cgi_controls>`
	cgi_introduction               :ref:`MapServer CGI Introduction <cgi_introduction>`
	class                          :ref:`CLASS <class>`
	community                      :ref:`Community Activities <community>`
	development                    :ref:`Development <development>`
	dgn                            :ref:`DGN <dgn>`
	documentation                  :ref:`MapServer 5.2.2 Documentation <documentation>`
	documentation_development      :ref:`Documentation Development Guide <documentation_development>`
	dotnet_compile                 :ref:`.NET MapScript Compilation <dotnet_compile>`
	download                       :ref:`Download <download>`
	dynamic_charting               :ref:`Dynamic Charting <dynamic_charting>`
	editing                        :ref:`Mapfile Editing <editing>`
	errors                         :ref:`Errors <errors>`
	example1-1                     :ref:`Example 1.1 <example1-1>`
	example1-1-map                 :ref:`Example1-1.map <example1-1-map>`
	example1-2                     :ref:`Example 1.2 <example1-2>`
	example1-2-map                 :ref:`Example1-2.map <example1-2-map>`
	example1-3                     :ref:`Example 1.3 <example1-3>`
	example1-3-map                 :ref:`Example1-3.map <example1-3-map>`
	example1-4                     :ref:`Example 1.4 <example1-4>`
	example1-4-map                 :ref:`Example1-4.map <example1-4-map>`
	example1-5                     :ref:`Example 1.5 <example1-5>`
	example1-5-map                 :ref:`Example1-5.map <example1-5-map>`
	example1-6                     :ref:`Example 1.6 <example1-6>`
	example1-6-map                 :ref:`Example1-6.map <example1-6-map>`
	example1-7                     :ref:`Example 1.7 <example1-7>`
	example1-7-map                 :ref:`Example1-7.map <example1-7-map>`
	example1-8                     :ref:`Example 1.8 <example1-8>`
	example1-8-map                 :ref:`Example1-8.map <example1-8-map>`
	expressions                    :ref:`Expressions <expressions>`
	faq                            :ref:`FAQ <faq>`
	fastcgi                        :ref:`FastCGI <fastcgi>`
	feature                        :ref:`FEATURE <feature>`
	filter_encoding                :ref:`WFS Filter Encoding <filter_encoding>`
	flash                          :ref:`Flash Output <flash>`
	fontset                        :ref:`FONTSET <fontset>`
	format_types                   :ref:`Data Format Types <format_types>`
	genindex                       :ref:`genindex`
        git                            :ref:`GitHub <git>`	
	gloss                          :ref:`Glossary <gloss>`
	gml                            :ref:`GML <gml>`
	gpx                            :ref:`GPS Exchange Format (GPX) <gpx>`
	grid                           :ref:`GRID <grid>`
	html_legend                    :ref:`HTML Legends with MapServer <html_legend>`
	iis                            :ref:`IIS Setup for MapServer <iis>`
	imagemaps                      :ref:`HTML Imagemaps <imagemaps>`
	include                        :ref:`INCLUDE <include>`
	inline                         :ref:`Inline <inline>`
	input                          :ref:`Data Input <input>`
	input_postgis                  :ref:`PostGIS/PostgreSQL <input_postgis>`
	installation                   :ref:`Installation <installation>`
	introduction                   :ref:`An Introduction to MapServer <introduction>`
	irc                            :ref:`IRC <irc>`
	join                           :ref:`JOIN <join>`
	kml                            :ref:`KML - Keyhole Markup Language <kml>`
	label                          :ref:`LABEL <label>`
	layer                          :ref:`LAYER <layer>`
	legend                         :ref:`LEGEND <legend>`
	legend_utility                 :ref:`legend <legend_utility>`
	license                        :ref:`License <license>`
	linux                          :ref:`Linux <linux>`
	lists                          :ref:`Mailing Lists <lists>`
	management                     :ref:`File Management <management>`
	map                            :ref:`MAP <map>`
	map_context                    :ref:`Map Context <map_context>`
	mapcache_formats               :ref:`MapCache Image Formats <mapcache_formats>`
	mapcache_jpeg_format           :ref:`MapCache JPEG Format <mapcache_jpeg_format>`
	mapcache_png_format            :ref:`MapCache PNG Format <mapcache_png_format>`
	mapcache_mixed_format          :ref:`MapCache Mixed PNG+JPEG Format <mapcache_mixed_format>`
	mapcache_caches                :ref:`MapCache Cache Backends <mapcache_caches>`
	mapcache_grids                 :ref:`MapCache Tile Grids <mapcache_grids>`
	mapcache_cache_sqlite          :ref:`MapCache Sqlite Caches <mapcache_cache_sqlite>`
	mapcache_cache_disk            :ref:`MapCache Disk Caches <mapcache_cache_disk>`
	mapcache_cache_memcache        :ref:`MapCache Memcache Caches <mapcache_cache_memcache>`
	mapcache_cache_tiff            :ref:`MapCache TIFF Caches <mapcache_cache_tiff>`
	mapcache_services              :ref:`MapCache Tile Services <mapcache_services>`
	mapcache_ve                    :ref:`MapCache VirtualEarth Quadkey Tile Service <mapcache_ve>`
	mapcache_tms                   :ref:`MapCache Tile Map Service <mapcache_tms>`
	mapcache_kml                   :ref:`MapCache Super-Overlay KML Services <mapcache_kml>`
	mapcache_wmts                  :ref:`MapCache OGC WMTS Service <mapcache_wmts>`
	mapcache_wms                   :ref:`MapCache OGC WMS Service <mapcache_wms>`
	mapcache_gmaps                 :ref:`MapCache GoogleMaps Tile Service <mapcache_gmaps>`
	mapcache_proxying              :ref:`MapCache Proxying Support <mapcache_proxying>`
	mapcache_dimensions            :ref:`MapCache Tileset Dimensions <mapcache_dimensions>`
	mapcache_featureinfo           :ref:`MapCache FeatureInfo Requests <mapcache_featureinfo>`
	mapcache_tile_assembling       :ref:`MapCache Tile Assembling <mapcache_tile_assembling>`
	mapcache_sources               :ref:`MapCache Input Sources <mapcache_sources>`
	mapcache_source_wms            :ref:`MapCache WMS Source <mapcache_source_wms>`
	mapcache_source_mapfile        :ref:`MapCache Native MapServer  Sources <mapcache_source_mapfile>`
	mapcache_http                  :ref:`MapCache HTTP Request <mapcache_http>`
	mapcontext_cgi                 :ref:`Map Context Files <mapcontext_cgi>`
	mapfile                        :ref:`Mapfile <mapfile>`
	mapfile_tuning                 :ref:`Mapfile <mapfile_tuning>`
	mapinfo                        :ref:`MapInfo <mapinfo>`
	mapscript                      :ref:`MapScript <mapscript>`
	mapscript_ows                  :ref:`MapScript Wrappers for WxS Services <mapscript_ows>`
	mapscript_tests                :ref:`MapScript Unit Testing <mapscript_tests>`
	mapserv                        :ref:`mapserv <mapserv>`
	modindex                       :ref:`modindex`
	msencrypt                      :ref:`msencrypt <msencrypt>`
	mysql                          :ref:`MySQL <mysql>`
	ntf                            :ref:`NTF <ntf>`
	oci                            :ref:`Oracle Spatial <oci>`
	oci_install                    :ref:`Oracle Installation <oci_install>`
	ogc                            :ref:`OGC Support and Configuration <ogc>`
	ogc_support                    :ref:`OGC Support <ogc_support>`
	ogr                            :ref:`OGR <ogr>`
	online_resource_wms            :ref:`More About the Online Resource URL <online_resource_wms>`
	optimization                   :ref:`Optimization <optimization>`
	osx                            :ref:`Mac OS X <osx>`
	output                         :ref:`Output Generation <output>`
	outputformat                   :ref:`OUTPUTFORMAT <outputformat>`
	pdf                            :ref:`PDF Output <pdf>`
	pgeo                           :ref:`ESRI Personal Geodatabase (MDB) <pgeo>`
	php                            :ref:`PHP MapScript <php_mapscript>`
	php_example                    :ref:`By Example <php_example>`
	php_install                    :ref:`PHP MapScript Installation <php_install>`
	php_install_example_steps      :ref:`Example Steps of a Full Windows Installation <php_install_example_steps>`
	projection                     :ref:`PROJECTION <projection>`
	psc                            :ref:`Project Steering Committee <psc>`	
	python                         :ref:`Python MapScript Appendix <python>`
	querying                       :ref:`Querying <querying>`
	querymap                       :ref:`QUERYMAP <querymap>`
	raster                         :ref:`Raster Data <raster>`
	raster_optimization            :ref:`Raster <raster_optimization>`
	reference                      :ref:`REFERENCE <reference>`
	rfc1                           :ref:`MS RFC 1: Technical Steering Committee Guidelines <rfc1>`
	rfc10                          :ref:`MS RFC 10: Joining the Open Source Geospatial Foundation <rfc10>`
	rfc11                          :ref:`MS RFC 11: Support for Curved Labels <rfc11>`
	rfc12                          :ref:`MS RFC 12: C code Unit tests <rfc12>`
	rfc13                          :ref:`MS RFC 13: Support of Sensor Observation Service in MapServer <rfc13>`
	rfc14                          :ref:`MS RFC 14: Relative Coordinates for INLINE features <rfc14>`
	rfc15                          :ref:`MS RFC 15: Support for thread neutral operation of MapServer/MapScript <rfc15>`
	rfc16                          :ref:`MS RFC 16: MapScript WxS Services <rfc16>`
	rfc17                          :ref:`MS RFC 17: Dynamic Allocation of layers, styles, classes and symbols <rfc17>`
	rfc18                          :ref:`MS RFC 18: Encryption of passwords in mapfiles <rfc18>`
	rfc19                          :ref:`MS RFC 19: Style & Label attribute binding <rfc19>`
	rfc2                           :ref:`MS RFC 2: Creating line features and/or shapes using WKT <rfc2>`
	rfc21                          :ref:`MS RFC 21: MapServer Raster Color Correction <rfc21>`
	rfc22a                         :ref:`MS RFC 22a: Feature cache for long running processes and query processing <rfc22a>`
	rfc23                          :ref:`MS RFC 23: Technical Steering Committee Guidelines <rfc23>`
	rfc24                          :ref:`MS RFC 24: Mapscript memory management <rfc24>`
	rfc24first                     :ref:`MS RFC 24: Mapscript memory management <rfc24first>`
	rfc25                          :ref:`MS RFC 25: Align MapServer pixel and extent models with OGC models <rfc25>`
	rfc26                          :ref:`MS RFC 26: Version 5 Terminology Cleanup <rfc26>`
	rfc27                          :ref:`MS RFC 27: Label Priority <rfc27>`
	rfc28                          :ref:`MS RFC 28: Redesign of LOG/DEBUG output mechanisms <rfc28>`
	rfc29                          :ref:`MS RFC 29: Dynamic Charting Capability <rfc29>`
	rfc3                           :ref:`MS RFC 3: Feature Layer Plug-in Architecture <rfc3>`
	rfc30                          :ref:`MS RFC 30: Support for WMS 1.3.0 <rfc30>`
	rfc31                          :ref:`MS RFC 31: Loading MapServer Objects from Strings <rfc31>`
	rfc32                          :ref:`MS RFC 32: Support for Anti-Grain Geometry (AGG) Rendering Engine <rfc32>`
	rfc33                          :ref:`MS RFC 33: Removing msLayerWhichItems() from maplayer.c <rfc33>`
	rfc39                          :ref:`MS RFC 39: Support of WMS/SLD Named Styles <rfc39>`
	rfc4                           :ref:`MS RFC 4: MapServer Raster Resampling <rfc4>`
	rfc40                          :ref:`MS RFC 40: Support Label Text Transformations <rfc40>`
	rfc41                          :ref:`MS RFC 41: Support of WCS 1.1.x Protocol <rfc41>`
	rfc42                          :ref:`MS RFC 42: Support of Cookies Forwarding <rfc42>`
	rfc43                          :ref:`MS RFC 43: Direct tile generation for Google Maps and Virtual Earth API <rfc43>`
	rfc44                          :ref:`MS RFC 44: Restore URL modification of mapfiles to pre-5.0 levels <rfc44>`
	rfc45                          :ref:`MS RFC 45: Symbology, Labeling, and Cartography Improvements <rfc45>`
	rfc46                          :ref:`MS RFC 46: Migrate Website to OSGeo <rfc46>`
	rfc47                          :ref:`MS RFC 47: Move IGNORE_MISSING_DATA to run-time configuration <rfc47>`
	rfc48                          :ref:`MS RFC 48: GEOTRANSFORM Geometry operations <rfc48>`
	rfc49                          :ref:`MS RFC 49: Symbology, Labeling, and Cartography Improvements <rfc49>`
	rfc5                           :ref:`MS RFC 5: MapServer Horizon Reprojection Improvements <rfc5>`
	rfc50                          :ref:`MS RFC 50: OpenGL Rendering Support <rfc50>`
	rfc51                          :ref:`MS RFC 51: XML Mapfile Format <rfc51>`
	rfc53                          :ref:`MS RFC 53: Guidelines for MapScript method return values <rfc53>`
	rfc54                          :ref:`MS RFC 54: Rendering Interface API <rfc54>`
	rfc55                          :ref:`MS RFC 55: Improve control of output resolution <rfc55>`
	rfc56                          :ref:`MS RFC 56: Tighten control of access to mapfiles and templates <rfc56>`
	rfc6                           :ref:`MS RFC 6: Color Range Mapping of Continuous Feature Values <rfc6>`
	rfc7                           :ref:`MS RFC 7: MapServer CVS Commit Management <rfc7>`
	rfc7.1                         :ref:`MS RFC 7.1: MapServer SVN Commit Management <rfc7.1>`
	rfc8                           :ref:`MS RFC 8: Pluggable External Feature Layer Providers <rfc8>`
	rfc9                           :ref:`MS RFC 9: Item tag for query templates <rfc9>`
	rfcs                           :ref:`Request for Comments <rfcs>`
	runsub                         :ref:`Run-time Substitution <runsub>`
	s57                            :ref:`S57 <s57>`
	scalebar                       :ref:`SCALEBAR <scalebar>`
	scalebar_utility               :ref:`scalebar <scalebar_utility>`
	sdts                           :ref:`SDTS <sdts>`
	search                         :ref:`search`
	section1                       :ref:`Section 1: Static Maps and the MapFile <tutorial_section1>`
	section2                       :ref:`Section 2: CGI variables and the User Interface <tutorial_section2>`
	shapefiles                     :ref:`ESRI Shapefiles (SHP) <shapefiles>`
	shp2img                        :ref:`shp2img <shp2img>`
	shptree                        :ref:`shptree <shptree>`
	shptreevis                     :ref:`shptreevis <shptreevis>`
	sld                            :ref:`SLD <sld>`
	sortshp                        :ref:`sortshp <sortshp>`
	sos_server                     :ref:`SOS Server <sos_server>`
	source                         :ref:`Source <source>`
	sponsors                       :ref:`Sponsors <sponsors>`
	style                          :ref:`STYLE <style>`
	styleitemauto-label-styles     :ref:`Accessing OGR STYLEITEMAUTO Label Styles Through MapScript <styleitemauto-label-styles>`
	svg                            :ref:`SVG <svg>`
	svn                            :ref:`Subversion <svn>`
	swig                           :ref:`SWIG MapScript API Reference <swig>`
	sym2img                        :ref:`sym2img <sym2img>`
	sym_construction               :ref:`Cartographic Symbol Construction with MapServer <sym_construction>`
	sym_examples                   :ref:`Symbology Examples <sym_examples>`
	symbol                         :ref:`SYMBOL <symbol>`
	template                       :ref:`Templating <template>`
	testing                        :ref:`Testing <testing>`
	tiger                          :ref:`USGS TIGER <tiger>`
	tile4ms                        :ref:`tile4ms <tile4ms>`
	tile_mode                      :ref:`Tile Mode <tile_mode>`
	tileindex                      :ref:`Tile Indexes <tileindex>`
	tutorial                       :ref:`MapServer Tutorial <tutorial>`
	unix                           :ref:`Compiling on Unix <unix>`
	utilities                      :ref:`Utilities <utilities>`
	variable_sub                   :ref:`Variable Substitution <runsub>`
	vector                         :ref:`Vector Data <vector>`
	vector_optimization            :ref:`Vector <vector_optimization>`
	vim                            :ref:`VIM Syntax <vim>`
	virtual_vector                 :ref:`Virtual Spatial Data <virtual_vector>`
	wcs_format                     :ref:`WCS Use Cases <wcs_format>`
	wcs_server                     :ref:`WCS Server <wcs_server>`
	web                            :ref:`WEB <web>`
	wfs                            :ref:`WFS <wfs>`
	wfs_client                     :ref:`WFS Client <wfs_client>`
	wfs_server                     :ref:`WFS Server <wfs_server>`
	win32                          :ref:`Compiling on Win32 <win32>`
	windows                        :ref:`Windows <windows>`
	wms_capabilities               :ref:`Validate the Capabilities Metadata <wms_capabilities>`
	wms_client                     :ref:`WMS Client <wms_client>`
	wms_server                     :ref:`WMS Server <wms_server>`
	wms_time                       :ref:`WMS Time <wms_time>`
	wrapper                        :ref:`A Simple CGI Wrapper Script <wrapper>`
	============================   =============================================================================================
