**2012-05-12 - MapServer 6.0.0 正式版发布**

MapServer 6.0.0 已经发布正式版。详情参见 :ref:`the release announcement <announce-6-0>` ，也可至 :ref:`download` 去获取拷贝。

**2011-04-13 - MapServer 6.0.0-beta6 发布**

MapServer 6.0.0-beta6 已经发布。详情参见 `the release announcement <http://lists.osgeo.org/pipermail/mapserver-users/2011-April/068475.html>`__ ，也可至 :ref:`download` 去获取拷贝。

**2011-03-15 - MapServer 项目委员会参加蒙特利尔极限编码活动**

MapServer项目委员会的成员们参加了 `Montreal Code Sprint <http://wiki.osgeo.org/wiki/Montreal_Code_Sprint_2011>`__ ，该活动是由PostGIS，GDAL，libLAS，GeoPrisma，和MapServer开发者团队联合参加的国际会议。

**2011-01-17 - MapServer 5.6.6 正式版发布**

MapServer 5.6.6 已经发布正式版。详情参见 `the release announcement <http://lists.osgeo.org/pipermail/mapserver-users/2011-January/067705.html>`__ ，也可至 :ref:`download` 去获取拷贝。

**2010-07-14 - MapServer 5.6.5 正式版发布，修复了5.6.4版中的一个尺度计算的问题**

MapServer 5.6.5 已经发布正式版，修复了5.6.4版中的一个尺度计算问题。详情参见 `Announcement <http://lists.osgeo.org/pipermail/mapserver-users/2010-July/066134.html>`__ ，也可至 :ref:`download` 去获取拷贝。

**2010-07-09 - MapServer 5.6.4和4.10.6正式版发布并带来了安全性更新**

MapServer 5.6.4和4.10.6 已经发布了正式版，包含了重要的安全性更新。详情参见 `Announcement <http://lists.osgeo.org/pipermail/mapserver-users/2010-July/066052.html>`__ ，也可至 :ref:`download` 去获取拷贝。

**2010-03-22 - MapServer 5.6.3 正式版发布**

MapServer 5.6.3 已经发布了正式版，详情参见 `the release announcement <http://lists.osgeo.org/pipermail/mapserver-users/2010-March/064997.html>`__ ，也可至:ref:`download` 去获取拷贝。

**2010-02-20 - MapServer 项目委员会参加纽约极限编码活动**

MapServer项目委员会的成员们参加了 `New York Code Sprint <http://wiki.osgeo.org/wiki/New_York_Code_Sprint_2010>`__ ，该活动是由PostGIS，GDAL，libLAS，GeoPrisma，和MapServer开发者团队联合参加的国际会议。

**2010-01-08 - MapServer 5.6.1 正式版发布**

MapServer 5.6.1 已经发布了正式版，详情参见 `the release announcement <http://lists.osgeo.org/pipermail/mapserver-users/2010-January/064120.html>`__ ， 也可至:ref:`download` 去获取拷贝。

**2009-12-18 - MapServer 5.6.0 正式版发布**

MapServer 5.6.0 已经发布了正式版，详情参见 `the release announcement <http://lists.osgeo.org/pipermail/mapserver-users/2009-December/064001.html>`__ ，也可至 ref:`download` 去获取拷贝。
