language: python
python: 3.9
dist: focal
env:
  global:
  - secure: gZkWb6ohPuN9Hrry+MuGbM3/yOAp13XaBlmRSYuqwo93moYKRRIVU5VDOKA/WRJdmHpsZt8PAETupiGsxSsbq5cb/0VKxYTw8eyGURD2K3zywDsrDGZRxk2u3K16HF4QneZAd+Q4ZnI5yUhUtzoNHJ3OagmFTL47CVEGqpCEDPg=
  - secure: N7YlUvnESLEYgYEy/shBQM+o5ONePG7iG7nnisoI2Wau+YbeCdYlLhM3EwytnCdvg9vj4Jwywjmc/8SaBiDLJp4diRYZUw67Qm/39auITH+MJGMJaz1WnBYTB8ypzPYTvmJrqityNFsvDoLDGAkEHh04oktDdvSbW42X7RwVHp4=
  - secure: f5Ugm6c9C0bkpHph8aPePW5BdlUuQCYL8PRgT3kgz7ccgW21gqRp12bGAp0Go9kEYxxEH+yL0J0n1JJ1yFOtRep0HT1pbblXzNUZGcazpYkDVmDHU5D1ZNlV6k0gvTT05C49SbU7Z6W0htPdn87AxhdIGzmwevhdLTJpiJD+MV4=
  - secure: c0m3a69vvkO/wgO4ZiexcADP1LHplaV+0oNTgIuQHDfhIErKK1xJJbKuhHy6dbQJXqwsZKmSzfMVzOp/1wBkv2lVIBXX4VvKIaLO8oapHwHqlXEpkXmaRg6P9Nny3CUW6a83GRIKaR1/h0CA8tc4Z1X2kxd148r7ih6pdOSOE2o=
  - secure: AyA1ZWvhAASGom1hrrN9pl/TVXxcoNfW3vr76DQRjYz/yeYU0OnEaFi7w2aWzhevoQ5ewuUPfldioAtnnnlZMe204Q+1ioMyDJwG6g1cK3seHlndMDG4nD8eG39V9DFHgm2J3WaypIF+X/iYixcMcUQyb5cDb5Wk7KwSR9mQzCM=
  - secure: AR2KiGtTiR1hHRia4/jNJMH19kzoWTkZGXwdzAOhtfiB1Q/RlCacCeoz5mtyqphYWnJH98Euo5m20p6qa2xuKGeZbBcX3xtuW7UNu1H+XshSMfYcz0gQ85t3JqSV7aRyeFEHGmgNnQddFb8iAqglgohJLHqazRvmyRqqIcYDyDs=
  - secure: QzQwzqcZknwKoQk8VkRwOLlJRKu4ajO2v+Op6K9QbQL4vbOIolyQf8mDpLEEjqWXB1HEdutkD+sEBjV0pP87lWfUHu+RCOxvxLPxRulQxoMBoqDdzWipM3Pdbgn/2Rpdq6nTU6rTIRj80MjMPNStkho4GC60wtBkxPckLAJD9Fo=
  - secure: Q2RqvTlja43mmpiog4d6VYKo1QfFjl6Xl6vy/7eX2Nx0dBFk1f5ii6QwreQpqWd2dS1pzIDF1Kew+iI7shxWQ+L496J8//SH9zkPwyt8b6kAXNwpj18kaSn53OV+BKuqe52Kh/dDh16JWN2i2bPDk7pMBT8t08gyWry1Cc8mWoU=
  - secure: FSMxM2f4gi15+hg0EWPTrPmdStYudRxIxvAvfSjrZk0yP7Op8Mlxo2sy0+EBhCR2TQz6DzSU6YDRIN3pOpuR/GO/ne2FBVLeG/k/2Uvm9Z3T6lsmXhjS5zGtD+kAGcBghk8a2G6I/yVbjezUlW4h5ku34sGRxM7R9E626+tF0FM=
  - secure: RLLsIC/csyLgPMjR7NUY9niPC0FOm3WguyR5zYn5EDRtnlvWPSi4dFyOq0LQgn09M3GJ+uTF/UYPxaXZCS4YTBBIb+UXaQvGHDiffj0TFizgtJK+aVO+DZkWL1S6RJ3syUzV8O/pn1Is6KwzqwKxiMkYap4qtT1dsRM28C0ycm4=
  - secure: JqC+xfR/8IMrV5I3wfWvc7OpY7XnUESo13A6KSVBJE3DtnEJCib0fF3/qgHzr6bFfRh8PpPak2qC/uhcLk6NB/6Vwyge4ZAgPengiWf0yN7aajNBrX9kxH27lU+fFttsOfWHHQRhMu8yYEhP7vZhoYaUgJ3+bcCh1geahYm8Lsg=
  - secure: N47bvQKpoHJrbNV0ibRGY2PPQhw/7hNphIRtH67smkog4SL3gLQBJPLo8IYjl+GVh0sRNq2xNCfUKJMzOozZyzgnvXfMHdWqLRPBDm6MumloESVMw5sxjwTZGABwY6akhDiAomvPHrmyNPzR38+fUDKBUpBiu5qR6vSlAOWtvk8=
  - secure: OiBMi8Lo0crnkvaWejgeh3vKtxcsOjdgughtS4szR/NqVwoJZuDttnBZU+N+2PVV0o6oDaI5HFUQJrcS5UvhC/Dn2Di5IQUQor6Nye6Q8SXHF9KaluugMzEQhBpLi7kxXCPX3XQsbCLmDrMVLKURRdw44lLrCDAmqT0kGn1jBmo=
  - secure: Oicf1y5W/EsxeNZG45LeSE00+PHH7T8DC1LzlstsuL/njU6zW17iiGoVpR2Tn7xfvfHqdJUb+3tBTpxxaNRiuiELtSqij9yW1OO7c4xhbqlINDK43YxLIS5UWaViK/sZPQHpuVprwCyD8jHckLUfNsC4PLvn9nVQf0dFp2267Rw=
  - secure: TxGvIa8IXkq65yxP47kqZadOmMNjbrNTf2sFM6Trv5UraJnZVU6vrzxBpHHKsxIweKDG5eHbwECRIVWUHR7k9Wd26HkMhACdvzqozHXjQoJQExB/7KDhzSly/XCqMAGJwxsJVIsJj9Vhy5uV46v5fAcatDAecoYmKpNreZXI0BI=
  - secure: Jniu1nBohlVwnmFEgrsaJQ7Jy4jSFkqLGKo+pPi+otlAxwZJeLeNlglDE9GVUzhRCNxVXyWgq/pf9+gjUESWoSm1FSF/z5hQOQA/Ws2M8jBlxNGxhECpMi5+BHl59f6yLwrOOFzmoadtk59kBUI+3phcRFqdgYkVs65GzqxSYAc=
  - secure: TwkGo10XmDPDU8RMXuIu2Fohl9x8qW4tX1Pp6Ix4FQXQToBueMmFaM7EMasQM+LN6FkqyIcMkJhGRzfft1P9f+/TBmV6tOAnWKzHHJ1QznISLiO8jle7FcK5Usrhq76DtnSx0o0E2Nmgw/BDXWOk2C0S3Rs/1Bm9WJfuVwkgKkE=
  - secure: I1ozqvcOyO00r3SUTwpWqGk2uXoD0wmigl13JIuIHjLwiGWe9IeRePHCc+rrZzjKcOdu9QB2Tlo7ONkRUqQVTEfj3Lfr1QM3FDAaOVcDpPNycQYs0oD96WiZr4A/hWVEvFLCWYmjY/qWgFvmFRNzUjxF0dJYwdHKvKSuxUPlK0A=
  - secure: UXqnHhzBCh6EP2+NMUWf9PEDrlcTPvCPA8ks6NBpSNOW/38Y9etp36ym/6XL5VvJ9hnXd+7AGhhVj5ddqbuScyAKwi3s4xWwZFXOlBIxM8nEbgNLQsYacC+9wZ6JJcLAjBibzTc1ULzYhT5/isvrOChwt5ebcTg4DjZfn07XW0g=
  - secure: X8Z+1XVDW1Rd9uIeUQgZnizRZ0+jN/1bGiLXRaK6tMyE7dpQaFJYZKIJ1g6HmKC/zB7Ja32mWujV1qtkLHZjoGyj0b3pxs+o2ZqHE0cSQTHSeH2+AEi8JOwglmvxewbwEBO5A+mCWBZBTrchiSrjiSGeBkpQfyMBOQWKsNc5Jss=
  - secure: BaFh874D/yC6aXakLPCHfTbBqDgCkA7WrMPAaj5yoOAFrKsYVVgF21Dc3eUHSvWXy6/HZdxzO0lOpJzgIoGbkINsH86w/fQthi4JfdxopowOEaOs9a1rSUT0MpIllXnRigPO42u+UZ2MOjP62sp/4Pu/LLj5U42ALNi3t+M5FgA=
  - secure: WG9zC2qVDIFF9t1FZ9LA3mwiisvyEJ9NX0xdhM1uOmI++k4dTlRf5H9HPV4HMIpVr0phlZK8eKj3N/1j4iL4FlteFfZaBZqMehuuTHQXaROytqJYZ5B8q10zlSHBNugr/hEDZM/Z8f950qH1xYvKYmyMqn0CPBrltfcqBWoCeEg=
  - secure: T5msa8CU0jcIs2m6sgZk48dppJcljWX9LFQlREqxMdW/cpUIpoi1/2Gkg2AE5GqLqiNhz7T/IKzzwnhB61uuIsoYDbT31S6wkUBEtZIUjhfvuqE007sr9r5rSAQsoz8geonmXejVj5c6Q7rjePLONRqZcUsXe7biL27hWP90s1s=

script:
- "./scripts/travis_build_docs.sh"
after_success:
- echo "$TRAVIS_SECURE_ENV_VARS"
- touch ./build/html/.nojekyll
- sh -c 'if test "$TRAVIS_SECURE_ENV_VARS" = "true" -a "$TRAVIS_BRANCH" = "branch-8-0"; then echo "publish website"; ./scripts/travis_add_deploy_key.sh; ./scripts/travis_deploy_website.sh build /tmp; fi'
notifications:
  irc:
    channels:
    - libera.chat#mapserver
    use_notice: true
    on_success: always
    on_failure: always
