12-30-2008 - New MapServer website is now live
..............................................................................

The new, improved MapServer website is now live!  Welcome to the new 
MapServer website.  Some of the major improvements include:

* An updated :ref:`gloss`
* A significantly improved :ref:`introduction`
* All documentation is now available in a single, 600+ page `PDF
  <./MapServer.pdf>`__
* More internal document referencing, better styling, and mapfile styling, 
* Simpler organizational structure

12-16-2008 - MapServer Graduates OSGeo Incubation
..............................................................................

MapServer recently graduated OSGeo's Incubation process.  Incubation 
includes ensuring items like code provenance and community contribution.  
See the `announcement`_ for more details.

.. _`announcement`: http://lists.osgeo.org/pipermail/mapserver-announce/2008-December/000015.html

12-08-2008 - MapServer 5.2.1 released
..............................................................................

MapServer 5.2.1 has been released.  See the `release notice`_ for more 
information.  Navigate to :ref:`download` to obtain the source code or 
binaries.

.. _`release notice`: http://lists.osgeo.org/pipermail/mapserver-users/2008-December/058757.html