2-18-2009 - MapServer 5.4 beta 1 is released
..............................................................................

MapServer 5.4 beta 1 has been released.  See the 
`Changelog <http://trac.osgeo.org/mapserver/browser/tags/rel-5-4-0-beta1/mapserver/HISTORY.TXT>`__ 
for more details and head to :ref:`download` to obtain a copy.  

12-30-2008 - New MapServer website is now live
..............................................................................

The new, improved MapServer website is now live!  Welcome to the new 
MapServer website.  Some of the major improvements include:

* An updated :ref:`gloss`
* A significantly improved :ref:`introduction`
* All documentation is now available in a single, 600+ page `PDF
  <./MapServer.pdf>`__
* More internal document referencing, better styling, and mapfile styling, 
* Simpler organizational structure

12-16-2008 - MapServer Graduates OSGeo Incubation
..............................................................................

MapServer recently graduated OSGeo's Incubation process.  Incubation 
includes ensuring items like code provenance and community contribution.  
See the `announcement`_ for more details.

.. _`announcement`: http://lists.osgeo.org/pipermail/mapserver-announce/2008-December/000015.html
