2009-10-01 - MapServer 5.6.0-beta2 is released
..............................................................................

MapServer 5.6.0-beta2 has been released.  See `the release announcement <http://lists.osgeo.org/pipermail/mapserver-users/2009-October/062991.html>`__ 
for more details and head to :ref:`download` to obtain a copy.

Once again, we need your help to test this new beta. Please see the 
annoncement linked above for more details on areas that need special attention.

2009-09-24 - MapServer 5.6.0-beta1 is released
..............................................................................

The MapServer Team is pleased to announce the release of the first beta 
for the 5.6.0 release. This is the first of three planned beta releases.

We need your help to ensure a high quality product so please help out by 
testing your applications with this new code base.

See `the release announcement <http://lists.osgeo.org/pipermail/mapserver-users/2009-September/062916.html>`__ 
for more details and head to :ref:`download` to obtain a copy.

2009-07-24 - MapServer 5.4.2 is released
..............................................................................

MapServer 5.4.2 has been released.  See the
`Changelog <http://trac.osgeo.org/mapserver/browser/tags/rel-5-4-2/mapserver/HISTORY.TXT>`__
for more details and head to :ref:`download` to obtain a copy.

2009-06-01 - MapServer 5.4.1 is released
..............................................................................

MapServer 5.4.1 has been released.  See the
`Changelog <http://trac.osgeo.org/mapserver/browser/tags/rel-5-4-1/mapserver/HISTORY.TXT>`__
for more details and head to :ref:`download` to obtain a copy.

2009-04-22 - MapServer 5.4 is released
..............................................................................

MapServer 5.4 has been released.  See the
`Changelog <http://trac.osgeo.org/mapserver/browser/tags/rel-5-4-0/mapserver/HISTORY.TXT>`__
for more details and head to :ref:`download` to obtain a copy.

2009-03-26 - MapServer 5.2.2 and 4.10.4 security fixes are released
..............................................................................

MapServer 5.2.2 and 4.10.4 have been released, containing important security fixes.  See the
`Announcement <http://lists.osgeo.org/pipermail/mapserver-users/2009-March/060600.html>`__
for more details and head to :ref:`download` to obtain copies.

2009-03-08 - MapServer PSC Attend Toronto Code Sprint
..............................................................................

Members of the MapServer Project Steering Committee attend the `Toronto Code Sprint <http://wiki.osgeo.org/wiki/Toronto_Code_Sprint_2009>`__
event, an international meeting of GDAL, PostGIS, OpenLayers, and MapServer development teams.

2008-12-30 - New MapServer website is now live
..............................................................................

The new, improved MapServer website is now live!  Welcome to the new
MapServer website.  Some of the major improvements include:

* An updated :ref:`gloss`
* A significantly improved :ref:`introduction`
* All documentation is now available in a single, 600+ page `PDF
  <./MapServer.pdf>`__
* More internal document referencing, better styling, and mapfile styling,
* Simpler organizational structure

2008-12-16 - MapServer Graduates OSGeo Incubation
..............................................................................

MapServer recently graduated OSGeo's Incubation process.  Incubation
includes ensuring items like code provenance and community contribution.
See the `announcement`_ for more details.

.. _`announcement`: http://lists.osgeo.org/pipermail/mapserver-announce/2008-December/000015.html
