name: Build Documentation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.12

      - name: Build docs
        run: |
          pip install -r requirements.txt
          echo "GIT_BRANCH=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV
          ./scripts/ci_build_docs.sh

      - name: After success steps
        if: ${{ success() && github.event_name == 'push' && github.repository == 'MapServer/MapServer-documentation' && github.ref_name == 'branch-8-2' }}
        run: |
          # setup the SSH key
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

          touch ./build/html/.nojekyll

          # get the short commit tag
          sha=$(git rev-parse --short ${{ github.sha }})
          echo "publish website using $GIT_BRANCH branch and commit $sha"
          ./scripts/ci_deploy_website.sh build /tmp $sha
