2010-02-20 - El PSC de MapServer asiste al New York Code Sprint
..................................................................................................................

Los miembros del Comité Directivo del Proyecto MapServer (PSC) asisten al evento `New York Code Sprint <http://wiki.osgeo.org/wiki/New_York_Code_Sprint_2010>`__,
una reunión internacional de los equipos de desarrollo de PostGIS, GeoServer, GeoMOOSE y MapServer.

2010-01-08 - MapServer 5.6.1 ha sido liberado
..............................................................................

MapServer 5.6.1 ha sido liberado. Vea el `anuncio <http://lists.osgeo.org/pipermail/mapserver-users/2010-January/064120.html>`__ 
para obtener mas detalles y diríjase a la sección de :ref:`download` para obtener el software.

2009-12-18 - MapServer 5.6.0 ha sido liberado
..............................................................................

MapServer 5.6.0 ha sido liberado. Vea el `anuncio <http://lists.osgeo.org/pipermail/mapserver-users/2009-December/064001.html>`__ 
para obtener mas detalles y diríjase a la sección de :ref:`download` para obtener el software.

2009-07-24 - MapServer 5.4.2 ha sido liberado
..............................................................................

MapServer 5.4.2  ha sido liberado. Vea el
`Registro de cambios <http://trac.osgeo.org/mapserver/browser/tags/rel-5-4-2/mapserver/HISTORY.TXT>`__
para obtener mas detalles y diríjase a la sección de :ref:`download` para obtener el software.

2009-06-01 - MapServer 5.4.1 ha sido liberado
..............................................................................

MapServer 5.4.1 ha sido liberado. Vea el
`Registro de cambios <http://trac.osgeo.org/mapserver/browser/tags/rel-5-4-1/mapserver/HISTORY.TXT>`__
para obtener mas detalles y diríjase a la sección de :ref:`download` para obtener el software.

2009-04-22 - MapServer 5.4 ha sido liberado
..............................................................................

MapServer 5.4 ha sido liberado.  Vea el
`Registro de cambios <http://trac.osgeo.org/mapserver/browser/tags/rel-5-4-0/mapserver/HISTORY.TXT>`__
para obtener mas detalles y diríjase a la sección de :ref:`download` para obtener el software.

2009-03-26 - MapServer 5.2.2 y 4.10.4 son liberados con correcciones de seguridad importantes
.............................................................................................

MapServer 5.2.2 y 4.10.4 han sido liberados, corrigiendo fallos de seguridad importantes.  Vea el
`Anuncio <http://lists.osgeo.org/pipermail/mapserver-users/2009-March/060600.html>`__
para obtener mas detalles y diríjase a la sección de :ref:`download` para obtener el software.

2009-03-08 - El PSC de MapServer PSC asiste a la competencia de Codificación de Toronto
.......................................................................................

Los miembros del Comité Directivo del Proyecto Mapserver asistieron a la `Competencia de Codificación de Toronto <http://wiki.osgeo.org/wiki/Toronto_Code_Sprint_2009>`__
, una reunión internacional de los equipos de desarrollo de GDAL, PostGIS, OpenLayers y MapServer.

2008-12-30 - El nuevo sitio web de MapServer está en línea
..............................................................................

El nuevo y mejorado sitio de MapServer está ahora en línea!  Bienvenidos al nuevo
sitio de MapServer.  Algunas de las mejoras mas importantes incluyen:

* Un :ref:`gloss` actualizado
* Una mejora significativa en la :ref:`introduction`
* Toda la documentación esta disponible en un archivo `PDF
  <./MapServer.pdf>`__ único con mas de 600 páginas
* Mas referencias internas, un mejor estilo de documentación y de archivo map,
* Estructura organizacional simplificada

2008-12-16 - MapServer se gradúa del proceso de incubación de OSGeo
..............................................................................

MapServer se graduó recientemente del proceso de incubación de OSGeo.  La incubación
permite asegurar elementos como la procedencia del código y la contribución de la comunidad.
Vea el `anuncio`_ para más detalles.

.. _`anuncio`: http://lists.osgeo.org/pipermail/mapserver-announce/2008-December/000015.html